export const eventDetails = {
    Event1: {
      image: "./src/assets/placeholder.png",
      title: "Pixel Craft",
      tagline: "Design, Innovate, Create",
      description:
        "The ultimate UI/UX design challenge! Create intuitive, visually stunning interfaces for real-world apps. Open to all skill levels, this event lets you showcase your expertise in user experience, wireframing, and prototyping. Design a mobile or web app based on a theme, judged on creativity, usability, and innovation. ",
      fee: 749,
      price_pool: 32000,
      event_head: "Bhrigu Gupta",
      event_head_number: "+91 70069 01099",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event2: {
      image: "./src/assets/placeholder.png",
      title: "Pitchathon",
      tagline: "Your Idea, Your Empire",
      description: "Have a game-changing startup idea? The Pitchathon is your ultimate stage to showcase it! Whether it's a disruptive tech solution, an innovative business model, or a sustainable product, this event gives you the chance to impress a panel of industry experts and potential investors. ",
      fee: 749,
      price_pool: 22000,
      event_head: "Rohan S Kumar",
      event_head_number: "+91 99018 04849",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event3: {
      image: "./src/assets/placeholder.png",
      title: "CodeRush",
      tagline: "24 Hour Software Hackathon",
      description: "A coding marathon like no other! Teams will brainstorm, develop, and present an innovative software solution within 24 hours. Creativity, problem-solving, and technical skills will be put to the test as you race against time to build something revolutionary. Think you have the next big tech idea? ",
      fee: 1249,
      price_pool: 45000,
      event_head: "Pavan K",
      event_head_number: "+91 77608 95008",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event4: {
      image: "./src/assets/placeholder.png",
      title: "HardWired",
      tagline: "24 Hour Hardware Hackathon",
      description: "A test of pure innovation, this hackathon challenges you to build a working hardware prototype in just 24 hours! From IoTto robotics, your project should solve real-world problems using cutting-edge technology. The best prototype wins—will your invention change the future? ",
      fee: 1249,
      price_pool: 60000,
      event_head: "Satvik K R",
      event_head_number: "+91 94823 80560",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A", 
      img: "src/assets/placeholder.png",    
    },
    Event5: {
      image: "./src/assets/placeholder.png",
      title: "Pitchathon",
      tagline: "Your Idea, Your Empire",
      description: "",
      fee: 749,
      price_pool: 32000,
      event_head: "Bhrigu Gupta",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event6: {
      image: "./src/assets/placeholder.png",
      title: "Dronetrix Daylight",
      tagline: "Skybound Precision Challenge",
      description: "Test your drone piloting skills in an intense aerial racecourse filled with hoops, tunnels, and altitude shifts! Maneuver through tight corners and obstacles while maintaining full control. Precision, agility, and speed will determine the champion—one wrong move and it's game over! ",
      fee: 999,
      price_pool: 35000,
      event_head: "Bhuvan A",
      event_head_number: "+91 98803 11801",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event7: {
      image: "./src/assets/placeholder.png",
      title: "Dronetrix Daylight",
      tagline: "First-Person Thrill In The Dark",
      description: "The stakes get higher when the sun goes down! Race your FPV drone through a neon-lit obstacle course in total darkness, relying only on real-time camera feed. With extreme speed and unpredictable twists, this night race is not for the faint of heart. Only the most skilled pilots will emerge victorious! ",
      fee: 999,
      price_pool: 50000,
      event_head: "Bhuvan A",
      event_head_number: "+91 98803 11801",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event8: {
      image: "./src/assets/placeholder.png",
      title: "Humpty Dumpty",
      tagline: "Egg Drop Engineering Challenge",
      description: "It's survival of the smartest! Using only provided materials, participants must build a protective structure that keeps an egg from breaking when dropped from extreme heights. With each successful round, the drop height increases. Light and compact makes you win proving engineering defy gravity. ",
      fee: 499,
      price_pool: 10000,
      event_head: "Kothareddy Vamshidhar Reddy",
      event_head_number: "+91 86397 02978",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event9: {
      image: "./src/assets/placeholder.png",
      title: "Project Expo",
      tagline: "Showcase Your Innovation To The World",
      description: "Your hard work deserves the spotlight! The Project Expo is a platform for students, engineers, and researchers to present their innovative projects to industry leaders and academia. Impress the judges with your creativity and execution! ",
      fee: 749,
      price_pool: 32000,
      event_head: "Harsha Vardhana T",
      event_head_number: "+91 98803 11801",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
    Event10: {
      image: "./src/assets/placeholder.png",
      title: "Maze Runner",
      tagline: "Decode, Navigate, Conquer",
      description: "Think fast, move faster! Your autonomous bot must find its way through a complex maze filled with twists, turns, and dead ends—all while racing against time. Will your bot's algorithm be smart enough to navigate through obstacles and reach the finish line before the others? ",
      fee: 999,
      price_pool: 32000,
      event_head: "Hrishikesh",
      event_head_number: "+91 84319 11666",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event11: {
      image: "./src/assets/placeholder.png",
      title: "Line Follower",
      tagline: "Stay On Track, Stay Ahead",
      description: "A test of precision and programming, this event challenges you to build an intelligent bot that can flawlessly follow a marked track at top speed. Sudden turns, sharp angles, and tricky intersections will test the limits of your bds efficiency. Can you master the path and leave the competition in the dust? ",
      fee: 999,
      price_pool: 32000,
      event_head: "Gagana S",
      event_head_number: "+91 83108 20700",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event12: {
      image: "./src/assets/placeholder.png",
      title: "RC Rally Car",
      tagline: "Speed Meets Strategy",
      description: "Get ready for an electrifying race through unpredictable terrains! RC Rally challenges you to design a high-speed remote-controlled car capable of tackling sharp turns, dirt tracks, and extreme ramps. Precision driving and technical mastery will be the keys to reaching the finish line first. ",
      fee: 999,
      price_pool: 45000,
      event_head: "Hemanth G",
      event_head_number: "+91 93530 00578",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event13: {
      image: "./src/assets/placeholder.png",
      title: "RC Plane",
      tagline: "Goal, Glide, Glory",
      description: "Take off into the skies in this exhilarating aerodynamics challenge! Teams must design and fly their own RC planes, navigating through checkpoints, performing aerial stunts, and landing with pinpoint accuracy. This event is the ultimate test of stability, control, and pilot expertise. ",
      fee: 999,
      price_pool: 60000,
      event_head: "Amogh B Hubballimath",
      event_head_number: "+91 79909 65318",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event14: {
      image: "./src/assets/placeholder.png",
      title: "Robo Wars",
      tagline: "Clash Of The Titans",
      description: "The ultimate battle of engineering and destruction! Teams will design and build combat robots that will go head-to-head in a high-intensity arena fight. With rotating blades, crushing claws, and deadly spinners, your bot must be strong enough to demolish the competition while withstanding brutal attacks. ",
      fee: 1800,
      price_pool: 100000,
      event_head: "Shivam",
      event_head_number: "+91 80507 65537",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event15: {
      image: "./src/assets/placeholder.png",
      title: "Robo Soccer",
      tagline: "Goal, Glide, Glory",
      description: "Experience the thrill of football with a futuristic twist! Robo Soccer pits teams against each other as they program autonomous bots to dribble, pass, and score against opponents. With real-time Al decision-making and strategic moves, your robots must outmaneuver the opposition to claim victory. ",
      fee: 1199,
      price_pool: 60000,
      event_head: "Amogh B Hubballimath",
      event_head_number: "+91 79909 65318",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",      
    },
    Event15: {
      image: "./src/assets/placeholder.png",
      title: "Robo Soccer",
      tagline: "Goal, Glide, Glory",
      description: "Experience the thrill of football with a futuristic twist! Robo Soccer pits teams against each other as they program autonomous bots to dribble, pass, and score against opponents. With real-time Al decision-making and strategic moves, your robots must outmaneuver the opposition to claim victory. ",
      fee: 1199,
      price_pool: 60000,
      event_head: "Amogh B Hubballimath",
      event_head_number: "+91 79909 65318",
      max_members: 4,
      date: "April 15, 2025",
      time: "10:00 AM",
      venue: "Conference Hall A",
      img: "src/assets/placeholder.png",
    },
};